### ISSUE TITLE
DEV - Q - Initial app model description

### ISSUE THREAD

**Issue by tiadal** [bohgman/DIVIMA#1]
Hello Be Secure GmbH, 
I have the following questions regarding the description:

- allocation of visitor cards, keys, and parking spaces. What do you mean with visitor cards? Is this considered as a VISIT with a unique ID?
- What would be the expected flow? Such as: 
  - new visitor comes
  - “visitor” registers and is created in the system
  - “Visit” is created in the system
  - After the visit is over “visitor” signs out
- Is there a list of finite available keys to be maintained? Can these be reassigned? Are these keys in reality “digital codes” or actual physical keys? 
- Is there a list of finite available parking slots to be maintained? Can these be reassigned? 
- If the same visitor visits a location every day, does she need to register every time or can a “visitor” be treated separately?
- Can the location be treated separately instead of just being an attribute of a visit? Like location is an object with attributes: Id, Name. This would make it easier to create/read/update/delete available locations.

Thanks

**Comment by tiadal** [comment]
![Assignment7b (1)](https://user-images.githubusercontent.com/73166570/122670913-a0699000-d1c4-11eb-8181-52d72d09ffa3.png)

**Comment by bohgman** [comment]
Hello Tiadal,

1) Visitor cards are to be issued by the gatekeeper for the duration of the visit. These do not require an ID. There is no need to create an extra class for cards. What is important is the visit ID and the type of visit.

2) The gatekeeper registers the visitor when arriving and when leaving. When leaving, assigned keys and parking spaces must be released again and the entry can no longer be edited. However, the entry remains in the list until it is deleted.

3) Since different keys are available in the various locations, it should be possible to create them individually and store them in the system. After a visitor leaves a location, a key (or parking space) is available again. They are physical objects like keys or key cards. It is important that the allocation is documented.

4) Like the keys. Same principle...

5) For this version it is not necessary to create a visitor directory. Each visit (no matter if more than once) can be registered as an extra visit. But if you want you can implement such a function. However, an entry should be able to be made quickly, even without having to create a visitor each time first.

6) Ok. I leave you the decision to treat this as a enumeration or separately.

Diagram: I agree with this archticture. Especially for internal employees it is a good idea to save them. But keep in mind that a visitor, besides the separate handling, can also be entered directly when creating a visit, to ensure a fast process and not to overwhelm older employees (e.g. for a one-time visitors). Maybe you can find a suitable solution for this...

Best regards

**Comment by tiadal** [comment]
Thanks for the feedback.

1. Ok, we will keep the visit itself an object and the type of visit is related to the visitor.
2. We'll keep a list of visits, that can be deleted but not edited after the visitor left.
3/4. We'll keep a list of keys and parking slots, adding the location as value for each and the status (given/available)
5/Diagram. Implementation on the front-end will be done in such a way that the operator could add a new visitor or look for one in the database in the same view, so no issues here.
6. We will probably treat it as a separate entity and offer CRUD funcionalities.

Best Regards

**Comment by bohgman** [comment]
Sounds good to me. I'm looking forward to seeing their results. 

 Best regards
